// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2anGXRliOz8v5wT_dZAYsMQUEJZ3ykb4',
    appId: '1:897687517302:web:701a99af0ad47138f50757',
    messagingSenderId: '897687517302',
    projectId: 'chatapp-91291',
    authDomain: 'chatapp-91291.firebaseapp.com',
    storageBucket: 'chatapp-91291.appspot.com',
    measurementId: 'G-YXW1W16DF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZ2Ncc_6prxvMAEPF6s0LuuPHZFeBuu8',
    appId: '1:897687517302:android:c131344458282a0df50757',
    messagingSenderId: '897687517302',
    projectId: 'chatapp-91291',
    storageBucket: 'chatapp-91291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_k4GnFs477d2kF6LY3_qbXx7Xns9DwA',
    appId: '1:897687517302:ios:1eb19ae3e92654f9f50757',
    messagingSenderId: '897687517302',
    projectId: 'chatapp-91291',
    storageBucket: 'chatapp-91291.appspot.com',
    iosBundleId: 'com.mobile.uniba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_k4GnFs477d2kF6LY3_qbXx7Xns9DwA',
    appId: '1:897687517302:ios:1eb19ae3e92654f9f50757',
    messagingSenderId: '897687517302',
    projectId: 'chatapp-91291',
    storageBucket: 'chatapp-91291.appspot.com',
    iosBundleId: 'com.mobile.uniba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2anGXRliOz8v5wT_dZAYsMQUEJZ3ykb4',
    appId: '1:897687517302:web:d425dd7f9669b163f50757',
    messagingSenderId: '897687517302',
    projectId: 'chatapp-91291',
    authDomain: 'chatapp-91291.firebaseapp.com',
    storageBucket: 'chatapp-91291.appspot.com',
    measurementId: 'G-NMKWVHKVKN',
  );
}
